Modifying test code since 'NoSuchMethodError' occured. https://buildhive.cloudbees.com/job/masayuki038/job/rajah/net.wrap_trap$rajah/10/testReport/junit/net.wrap_trap.rajah.protocol/RedisProtocolReaderTest/testClientSetWithMultiByteValue/